apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gw-nginx
    version: '1.0'
  name: gw-nginx-us-east1-us-east1-a
  namespace: mubench-realistic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gw-nginx
      app-t: gw-nginx-us-east1-us-east1-a
  template:
    metadata:
      labels:
        app: gw-nginx
        app-t: gw-nginx-us-east1-us-east1-a
        version: '1.0'
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-east1
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - us-east1-a
      containers:
      - image: nginx
        name: gw-nginx
        ports:
        - containerPort: 80
          name: http-nginx
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: config-volume
          readOnly: true
          subPath: nginx.conf
        - mountPath: /var/log/nginx
          name: log
      schedulerName: default-scheduler
      volumes:
      - configMap:
          name: gw-nginx
        name: config-volume
      - emptyDir: {}
        name: log
---
apiVersion: v1
kind: Service
metadata:
  name: gw-nginx
  namespace: mubench-realistic
spec:
  ports:
  - name: http-nginx
    nodePort: 31213
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gw-nginx
  type: NodePort
