@startuml
skinparam shadowing false
skinparam backgroundColor #FFFFFF
skinparam packageStyle rectangle
skinparam componentStyle rectangle
skinparam ArrowColor #2F4F4F
skinparam DefaultTextAlignment center

left to right direction

title C2 - Arquitectura mTLS inter-servicio S2 (simplificado)

actor "k6 S2 runner" as k6

node "Namespace mubench-real" {
  component "auth-service" as auth
  component "api-service" as api
  component "data-service" as data
  database "postgres" as db
}

k6 --> auth : HTTP NodePort 30184
k6 --> api : HTTP NodePort 30181
api --> data : llamada interna
data --> db : consulta SQL

@enduml
