server {
    listen 80;
    server_name _;

    # DNS interno de k8s
    resolver 10.152.183.10 valid=10s ipv6=off;

    # Logs útiles para benchmark
    log_format perf '$remote_addr [$time_local] '
                    '"$request" $status '
                    'rt=$request_time '
                    'uct=$upstream_connect_time '
                    'uht=$upstream_header_time '
                    'urt=$upstream_response_time';

    access_log /var/log/nginx/access.log perf;

    # Timeouts REALISTAS
    proxy_connect_timeout 2s;
    proxy_send_timeout    5s;
    proxy_read_timeout    5s;

    # Backpressure
    client_body_timeout 5s;
    client_max_body_size 1m;

    # Headers de trazabilidad
    proxy_set_header X-Request-ID $request_id;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;

    # ===============================
    # Entrada principal
    # ===============================
    location /api/ {
        proxy_pass http://service0.default.svc.cluster.local:3000/;
    }

    # Health del gateway
    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
