apiVersion: v1
data:
  workmodel.json: "{\n  \"api\": {\n    \"external_services\": [\n      {\n      \
    \  \"seq_len\": 1,\n        \"services\": [\n          \"auth\"\n        ],\n\
    \        \"probabilities\": {\n          \"auth\": 1.0\n        }\n      },\n\
    \      {\n        \"seq_len\": 1,\n        \"services\": [\n          \"sdb-data\"\
    \n        ],\n        \"probabilities\": {\n          \"sdb-data\": 1.0\n    \
    \    }\n      }\n    ],\n    \"internal_service\": {\n      \"api_function\":\
    \ {\n        \"jwt_secret\": \"mubench-dev-secret\",\n        \"rate_limit_enabled\"\
    : false,\n        \"rate_limit_rpm\": 600,\n        \"processing_latency_ms\"\
    : 10,\n        \"mean_response_size\": 2\n      }\n    },\n    \"request_method\"\
    : \"rest\",\n    \"workers\": 2,\n    \"threads\": 8,\n    \"replicas\": 1,\n\
    \    \"cpu-limits\": \"500m\",\n    \"cpu-requests\": \"200m\",\n    \"memory-limits\"\
    : \"256Mi\",\n    \"memory-requests\": \"128Mi\",\n    \"url\": \"api.mubench-realistic.svc.cluster.local\"\
    ,\n    \"path\": \"/api/v1\",\n    \"image\": \"msvcbench/microservice:latest\"\
    ,\n    \"namespace\": \"mubench-realistic\"\n  },\n  \"auth\": {\n    \"external_services\"\
    : [],\n    \"internal_service\": {\n      \"auth_function\": {\n        \"jwt_secret\"\
    : \"mubench-dev-secret\",\n        \"jwt_expire_minutes\": 30,\n        \"username\"\
    : \"demo\",\n        \"auth_latency_ms\": 5,\n        \"mean_response_size\":\
    \ 1\n      }\n    },\n    \"request_method\": \"rest\",\n    \"workers\": 2,\n\
    \    \"threads\": 8,\n    \"replicas\": 1,\n    \"cpu-limits\": \"300m\",\n  \
    \  \"cpu-requests\": \"100m\",\n    \"memory-limits\": \"128Mi\",\n    \"memory-requests\"\
    : \"64Mi\",\n    \"url\": \"auth.mubench-realistic.svc.cluster.local\",\n    \"\
    path\": \"/api/v1\",\n    \"image\": \"msvcbench/microservice:latest\",\n    \"\
    namespace\": \"mubench-realistic\"\n  },\n  \"sdb-data\": {\n    \"external_services\"\
    : [],\n    \"internal_service\": {\n      \"data_function\": {\n        \"query_latency_ms\"\
    : 20,\n        \"db_rows\": 10,\n        \"simulate_disk\": false,\n        \"\
    disk_write_block_count\": 100,\n        \"disk_write_block_size\": 512,\n    \
    \    \"tmp_file_name\": \"mub-data-tmp.txt\",\n        \"mean_response_size\"\
    : 5\n      }\n    },\n    \"request_method\": \"rest\",\n    \"workers\": 2,\n\
    \    \"threads\": 8,\n    \"replicas\": 1,\n    \"cpu-limits\": \"300m\",\n  \
    \  \"cpu-requests\": \"100m\",\n    \"memory-limits\": \"128Mi\",\n    \"memory-requests\"\
    : \"64Mi\",\n    \"url\": \"sdb-data.mubench-realistic.svc.cluster.local\",\n\
    \    \"path\": \"/api/v1\",\n    \"image\": \"msvcbench/microservice:latest\"\
    ,\n    \"namespace\": \"mubench-realistic\"\n  }\n}\n"
kind: ConfigMap
metadata:
  name: workmodel
  namespace: mubench-realistic
