apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    something: something
  labels:
    app: api
    version: '1.0'
    zone: default
  name: api-eu-west1-eu-west1-a
  namespace: mubench-realistic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      app-t: api-eu-west1-eu-west1-a
  template:
    metadata:
      annotations:
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
      labels:
        app: api
        app-t: api-eu-west1-eu-west1-a
        prometheus.io/scrape: 'true'
        version: '1.0'
        zone: default
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - eu-west1
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - eu-west1-a
      containers:
      - env:
        - name: APP
          value: api
        - name: ZONE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['zone']
        - name: K8S_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: PN
          value: '2'
        - name: TN
          value: '8'
        - name: COMM_PROTOCOL
          value: null
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: msvcbench/microservice:latest
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
        name: api
        ports:
        - containerPort: 8080
          name: http-mubpodport
        - containerPort: 8443
          name: https-mubpod
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/podinfo
          name: podinfo
        - mountPath: /app/MSConfig
          name: microservice-workmodel
        - mountPath: /app/MSConfig/InternalServiceFunctions
          name: microservice-internal-services
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 3
      volumes:
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
      - configMap:
          name: workmodel
        name: microservice-workmodel
      - configMap:
          name: internal-services
        name: microservice-internal-services
