apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: mubench-realistic
  labels:
    app: auth
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http-mubserviceport
  - port: 443
    targetPort: 8443
    name: https-mubserviceport
  - port: 51313
    targetPort: 51313
    name: grpc-mubserviceport
  selector:
    app: auth
